---
- name: UFW | Install package
  package:
    name: ufw
    state: present

- name: Allow SSH access
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Enable UFW (conditionally)
  community.general.ufw:
    state: enabled
  when: enable_ufw

- name: Disabel UFW (conditionally)
  community.general.ufw:
    state: disabled
  when: not enable_ufw
