---
- name: Update Debian packages
  ansible.builtin.include_role:
    name: debian-upgrade

- name: Deploy base Debian packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_packages }}"

- include_tasks: hostname.yml

- include_tasks: network-alias.yml

- name: Set local timezone
  timezone:
    name: "{{ system_timezone }}"

- name: Configure locale (if specified)
  block:
  - community.general.locale_gen:
      name: "{{ my_locale }}"
      state: present
  - blockinfile:
      path: "/home/{{ shell_user }}/.bashrc"
      block: |
        # set the locale
        LANG="{{ my_locale }}"
        LC_CTYPE="{{ my_locale }}"
        LC_ALL="{{ my_locale }}"
  when: not (my_locale == "")

- import_tasks: install-qemu-agent.yml
  notify:
    - reboot vm
  when: install_in_vm

- import_tasks: install-lh-prereq.yml
  when: install_lh_prereq

- import_tasks: disable-ipv6.yml

- name: P10k | Include p10k prompt style variables
  include_vars: "{{ p10k_style[p10k_prompt_style] }}.yml"

- import_tasks: install-zsh.yml

- name: Install and configure p10k
  block:
    - include_tasks: "p10k-install.yml"
    - include_tasks: "p10k-fonts.yml"
    - include_tasks: "p10k-configure.yml"
  when: install_p10k

- name: Install Neofetch
  ansible.builtin.package:
    name: neofetch
    state: present
  when: install_neofetch
- name: Enable Neofetch
  ansible.builtin.blockinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    block: |
      # Run neofetch at login and before Powerlevel10k instant prompt
      neofetch
    insertbefore: BOF
    marker_begin: "BEGIN NEOFETCH CONFIG FILE"
    marker_end: "END NEOFETCH CONFIG FILE"
    state: present
  become: true
  become_user: "{{ shell_user }}"
  when: install_neofetch

- import_tasks: enable-yama.yaml

- ansible.builtin.include_role:
    name: reboot

# TODO: echo \"Samsung SSD 870 QVO 8TB\" 190 C \"Samsung SSD 870 QVO 8TB\" | sudo tee -a /etc/hddtemp.db
# - name: Add Samsung SSD to hddtemp database
#   ansible.builtin.lineinfile:
#     path: /etc/hddtemp.db
#     regexp: '^870 QVO 8TB'
#     line: \"Samsung SSD 870 QVO 8TB\" 190 C \"Samsung SSD 870 QVO 8TB\"

# TODO: add lm-sensors modules:
# Chip drivers
# coretemp
