---
- name: APT | Update debian.sources
  # become: true
  # become_user: '{{ shell_user }}'
  template:
    src: debian.sources.j2
    dest: '/etc/apt/sources.list.d/debian.sources'
    mode: 'u=rw,go=r'
    force: yes
    backup: yes